package vista;

import controlador.DAO.PedidoDAO;
import javax.swing.JOptionPane;
import modelo.tabla.PedidosTabla;

public class Frm_SolicitudPedido extends javax.swing.JFrame {

    private PedidoDAO pedidoDAO = new PedidoDAO();
    private PedidosTabla pedidosTabla = new PedidosTabla();

    /**
     * Creates new form Frm_SolicitudPedido
     */
    public Frm_SolicitudPedido() {
        initComponents();
        cargarTabla();
    }

    public void aceptarPedido() {
        if (tblSolicitudPedido.getSelectedRow() != - 1) {
            pedidoDAO.setPedido(pedidoDAO.getPedidosPorEstado("PENDIENTE").get(tblSolicitudPedido.getSelectedRow()));
            pedidoDAO.getPedido().setEstado_pedido("EN PROCESO");
            if (pedidoDAO.editar(pedidoDAO.getPedido())) {
                JOptionPane.showMessageDialog(this, "Pedido aceptado exitosamente");
                pedidoDAO.setPedido(null);
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al momento de acpetar el pedido, por favor, intente nuevamente");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, primero seleccione un pedido de la tabla");
        }
    }
    
    public void verDetallesPedido() {
        if (tblSolicitudPedido.getSelectedRow() != - 1) {
            pedidoDAO.setPedido(pedidoDAO.getPedidosPorEstado("PENDIENTE").get(tblSolicitudPedido.getSelectedRow()));
            new Frm_DetallesPedido(pedidoDAO).setVisible(true);
            pedidoDAO.setPedido(null);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, primero seleccione un pedido de la tabla");
        }
    }

    public void cargarTabla() {
        pedidosTabla.setListaPedidos(pedidoDAO.getPedidosPorEstado("PENDIENTE"));
        tblSolicitudPedido.setModel(pedidosTabla);
        tblSolicitudPedido.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitudPedido = new javax.swing.JTable();
        btnVerDetalles = new javax.swing.JButton();
        btnAceptarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        tblSolicitudPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSolicitudPedido);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(12, 12, 470, 230);

        btnVerDetalles.setText("Ver Detalles");
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        jPanel3.add(btnVerDetalles);
        btnVerDetalles.setBounds(10, 260, 100, 22);

        btnAceptarPedido.setText("Aceptar Pedido");
        btnAceptarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPedidoActionPerformed(evt);
            }
        });
        jPanel3.add(btnAceptarPedido);
        btnAceptarPedido.setBounds(345, 260, 130, 22);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 500, 300);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(535, 344));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        verDetallesPedido();
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnAceptarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPedidoActionPerformed
        aceptarPedido();
    }//GEN-LAST:event_btnAceptarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_SolicitudPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_SolicitudPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_SolicitudPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_SolicitudPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_SolicitudPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarPedido;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolicitudPedido;
    // End of variables declaration//GEN-END:variables
}
