package vista;

import controlador.DAO.PedidoDAO;
import controlador.DAO.PersonaDAO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import modelo.tabla.ResultadosTabla;

public class Frm_Resultados extends javax.swing.JFrame implements Printable{

    private PedidoDAO pedidoDAO;
    private PersonaDAO personaDAO = new PersonaDAO();
    private ResultadosTabla resultadosTabla = new ResultadosTabla();
    
    /**
     * Creates new form Frm_Resultados
     */
    public Frm_Resultados() {
        initComponents();
    }
    
    public Frm_Resultados(PedidoDAO pedidoDAO) {
        this.pedidoDAO = pedidoDAO;
        initComponents();
        cargarCampos();
    }

    public void imprimir() {
        try {
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setPrintable(this);
            boolean verificarImpresion = pj.printDialog();
            if (verificarImpresion) {
                pj.print();
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "No se pudo imprimir los resultados, por favor, intente nuevamente", "ERROR EN LA IMPRESIÓN\n " + e, JOptionPane.INFORMATION_MESSAGE);

        }
    }

    public void cargarCampos() {
        
    }
    
    public void cargarTabla() {
        resultadosTabla.setListaExamenes(pedidoDAO.getPedido().getListaExamen());
        tblResultados.setModel(resultadosTabla);
        tblResultados.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelImpresion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSolicitante = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        panelImpresion.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel1.setText("Paciente:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 80, 16);

        jLabel2.setText("Médico solicitante:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 110, 16);

        lblSolicitante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblSolicitante);
        lblSolicitante.setBounds(150, 60, 240, 20);

        lblPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblPaciente);
        lblPaciente.setBounds(120, 20, 220, 20);

        jLabel3.setText("Edad:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(360, 20, 50, 16);

        lblEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblEdad);
        lblEdad.setBounds(430, 20, 70, 20);

        jLabel4.setText("Fecha:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 50, 16);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(70, 100, 150, 22);

        panelImpresion.add(jPanel2);
        jPanel2.setBounds(10, 10, 510, 140);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 470, 330);

        panelImpresion.add(jPanel3);
        jPanel3.setBounds(10, 170, 510, 370);

        jPanel1.add(panelImpresion);
        panelImpresion.setBounds(10, 10, 530, 560);

        btnCancelar.setText("Volver");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(20, 570, 90, 22);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimir);
        btnImprimir.setBounds(430, 570, 90, 22);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(558, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        imprimir();
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblSolicitante;
    private javax.swing.JPanel panelImpresion;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D g2d = (Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
//         g2d.scale(0.70, 0.90);
        panelImpresion.printAll(graphics);
        return PAGE_EXISTS;

    }
}
