package vista;

import controlador.DAO.CuentaDAO;
import controlador.DAO.RolDAO;
import controlador.Seguridad;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import modelo.Cuenta;
import modelo.Rol;

public class inicio_sesion extends javax.swing.JFrame {

    private CuentaDAO cuentaDAO = new CuentaDAO();
    private RolDAO rolDAO = new RolDAO();
    private Seguridad seguridad = new Seguridad();
    //private boolean sw = false;

    public inicio_sesion() {
        initComponents();
        cargarRoles();
    }

    public Cuenta buscarCuenta() {
        for (Object c : cuentaDAO.listarCuentas()) {
            if (this.txtClave.getText().equals(seguridad.Desencriptar(cuentaDAO.buscarCuenta((Cuenta) c).getClave()))
                    && this.txtUsuario.getText().equals(cuentaDAO.buscarCuenta((Cuenta) c).getUsuario())) {
                //sw = true;
                return (Cuenta) c;
            }
        }
        return null;
    }

    public void ingresarSistema() {
        Cuenta c = buscarCuenta();
        if (c == null) {
            JOptionPane.showMessageDialog(null, "Los dato/s ingresados son incorrectos", "ERROR: Autenticación", JOptionPane.WARNING_MESSAGE);
            this.txtUsuario.setText("");
            this.txtClave.setText("");
        } else {
            
            switch (c.getPersona().getRol().getNombre_rol()) {
                case "MEDICO":
                    PaginaPrincipalMedico form = new PaginaPrincipalMedico();
                    form.setVisible(true);
                    this.dispose(); break;
                case "ATENCION":
                    PaginaPrincipalMedico form1 = new PaginaPrincipalMedico();
                    form1.setVisible(true);
                    this.dispose(); break;
                case "LABORATORISTA":
                    PaginaPrincipalMedico form2 = new PaginaPrincipalMedico();
                    form2.setVisible(true);
                    this.dispose(); break;
                case "ADMINISTRADOR":
                    PaginaPrincipalMedico form3 = new PaginaPrincipalMedico();
                    form3.setVisible(true);
                    this.dispose(); break;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Usuario:");

        jLabel3.setText("Clave:");

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtClave)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnIniciarSesion)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnIniciarSesion)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        ingresarSistema();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    public void cargarRoles() {
        int aux = 0;
        if(rolDAO.numeroRoles()<=0){
            rolDAO.getRol().setNombre_rol("PERSONA");
        rolDAO.setRol(rolDAO.getRol());
        rolDAO.agregarRol(rolDAO.getRol());
        rolDAO.setRol(null);
        rolDAO.getRol().setNombre_rol("MEDICO");
        rolDAO.setRol(rolDAO.getRol());
        rolDAO.agregarRol(rolDAO.getRol());
        rolDAO.setRol(null);
        rolDAO.getRol().setNombre_rol("LABORATORISTA");
        rolDAO.setRol(rolDAO.getRol());
        rolDAO.agregarRol(rolDAO.getRol());
        rolDAO.setRol(null);
        rolDAO.getRol().setNombre_rol("ATENCION");
        rolDAO.setRol(rolDAO.getRol());
        rolDAO.agregarRol(rolDAO.getRol());
        rolDAO.setRol(null);
        rolDAO.getRol().setNombre_rol("ADMINISTRADOR");
        rolDAO.setRol(rolDAO.getRol());
        rolDAO.agregarRol(rolDAO.getRol());
        rolDAO.setRol(null);
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
